export const transactions = [
  {
    id: 1,
    date: "2024-08-15",
    type: "credit",
    description: "FDNY PAYROLL DIRECT DEP",
    transac: "Deposit",
    amount: 820,
  },
  {
    id: 2,
    date: "2024-08-20",
    type: "debit",
    description: "POS PURCHASE STOP & SHOP #2231 QUEENS NY",
    transac: "Card",
    amount: 132,
  },
  {
    id: 3,
    date: "2024-08-25",
    type: "debit",
    description: "SHELL OIL 204399 BRONX NY",
    transac: "Card",
    amount: 58,
  },
  {
    id: 4,
    date: "2024-09-01",
    type: "credit",
    description: "ZELLE TRANSFER FROM LISA MORRIS",
    transac: "Transfer",
    amount: 200,
  },
  {
    id: 5,
    date: "2024-09-05",
    type: "debit",
    description: "CHASE CREDIT CARD PAYMENT",
    transac: "Transfer",
    amount: 350,
  },
  {
    id: 6,
    date: "2024-09-13",
    type: "credit",
    description: "FDNY OVERTIME PAY",
    transac: "Deposit",
    amount: 720,
  },
  {
    id: 7,
    date: "2024-09-18",
    type: "debit",
    description: "POS PURCHASE HOME DEPOT #3321 BROOKLYN NY",
    transac: "Card",
    amount: 188,
  },
  {
    id: 8,
    date: "2024-10-01",
    type: "credit",
    description: "TAX REFUND US TREASURY 310",
    transac: "Deposit",
    amount: 920,
  },
  {
    id: 9,
    date: "2024-10-03",
    type: "debit",
    description: "ONLINE PAYMENT CONEDISON BILLPAY",
    transac: "Transfer",
    amount: 165,
  },
  {
    id: 10,
    date: "2024-10-13",
    type: "credit",
    description: "FDNY BI-WEEKLY PAYROLL DEP",
    transac: "Deposit",
    amount: 820,
  },
  {
    id: 11,
    date: "2024-10-20",
    type: "debit",
    description: "POS PURCHASE COSTCO WHOLESALE #1013",
    transac: "Card",
    amount: 276,
  },
  {
    id: 12,
    date: "2024-11-05",
    type: "credit",
    description: "UNIFORM EXPENSE REIMB FDNY",
    transac: "Deposit",
    amount: 480,
  },
  {
    id: 13,
    date: "2024-11-12",
    type: "credit",
    description: "FDNY PAYROLL DIRECT DEP",
    transac: "Deposit",
    amount: 820,
  },
  {
    id: 14,
    date: "2024-11-15",
    type: "debit",
    description: "UNITED HEALTHCARE PREMIUM",
    transac: "Transfer",
    amount: 315,
  },
  {
    id: 15,
    date: "2024-11-25",
    type: "debit",
    description: "POS PURCHASE APPLE STORE #R234 NEW YORK NY",
    transac: "Card",
    amount: 499,
  },
  {
    id: 16,
    date: "2024-12-02",
    type: "credit",
    description: "ZELLE TRANSFER FROM JASON MILLER",
    transac: "Transfer",
    amount: 320,
  },
  {
    id: 17,
    date: "2024-12-13",
    type: "credit",
    description: "FDNY PAYROLL DEP",
    transac: "Deposit",
    amount: 820,
  },
  {
    id: 18,
    date: "2024-12-20",
    type: "debit",
    description: "POS PURCHASE TARGET #5542 BROOKLYN NY",
    transac: "Card",
    amount: 243,
  },
  {
    id: 19,
    date: "2024-12-27",
    type: "debit",
    description: "NYC DEPT OF FINANCE EZPASS TOLLS",
    transac: "Transfer",
    amount: 95,
  },
  {
    id: 20,
    date: "2025-01-05",
    type: "credit",
    description: "INSURANCE CLAIM PAYMENT METLIFE",
    transac: "Deposit",
    amount: 600,
  },
  {
    id: 21,
    date: "2025-01-10",
    type: "debit",
    description: "ATM CASH WDWL 122 MAIN ST QUEENS NY",
    transac: "ATM",
    amount: 200,
  },
  {
    id: 22,
    date: "2025-01-15",
    type: "credit",
    description: "FDNY OVERTIME PAY",
    transac: "Deposit",
    amount: 840,
  },
  {
    id: 23,
    date: "2025-01-19",
    type: "debit",
    description: "POS PURCHASE BEST BUY #4411 BRONX NY",
    transac: "Card",
    amount: 415,
  },
  {
    id: 24,
    date: "2025-02-01",
    type: "credit",
    description: "ZELLE TRANSFER FROM KEVIN SMITH",
    transac: "Transfer",
    amount: 250,
  },
  {
    id: 25,
    date: "2025-02-13",
    type: "credit",
    description: "FDNY PAYROLL DIRECT DEP",
    transac: "Deposit",
    amount: 820,
  },
  {
    id: 26,
    date: "2025-02-18",
    type: "debit",
    description: "POS PURCHASE SHOPRITE #892 NEWARK NJ",
    transac: "Card",
    amount: 176,
  },
  {
    id: 27,
    date: "2025-02-28",
    type: "debit",
    description: "CHASE CREDIT CARD PAYMENT",
    transac: "Transfer",
    amount: 500,
  },
  {
    id: 28,
    date: "2025-03-05",
    type: "credit",
    description: "EXPENSE REIMBURSEMENT FDNY TRAINING",
    transac: "Deposit",
    amount: 300,
  },
  {
    id: 29,
    date: "2025-03-15",
    type: "credit",
    description: "FDNY PAYROLL DEP",
    transac: "Deposit",
    amount: 820,
  },
  {
    id: 30,
    date: "2025-06-20",
    type: "debit",
    description: "POS PURCHASE MCDONALD'S #1089 BRONX NY",
    transac: "Card",
    amount: 42,
  },
  {
    id: 31,
    date: "2025-06-10",
    type: "credit",
    description: "ZELLE TRANSFER FROM MARY JOHNSON",
    transac: "Transfer",
    amount: 200,
  },
  {
    id: 32,
    date: "2025-07-15",
    type: "credit",
    description: "FDNY BI-WEEKLY PAYROLL DEP",
    transac: "Deposit",
    amount: 820,
  },
  {
    id: 33,
    date: "2025-07-25",
    type: "debit",
    description: "POS PURCHASE DELTA AIRLINES JFK NY",
    transac: "Card",
    amount: 420,
  },
  {
    id: 34,
    date: "2025-08-12",
    type: "credit",
    description: "FDNY OVERTIME BONUS",
    transac: "Deposit",
    amount: 950,
  },
  {
    id: 35,
    date: "2025-08-15",
    type: "debit",
    description: "ATM CASH WDWL 81 BROADWAY NEW YORK NY",
    transac: "ATM",
    amount: 300,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2024-08-20",
    type: "credit",
    description: "ONLINE TRANSFER FROM CHK ####9876",
    transac: "Transfer",
    amount: 600,
  },
  {
    id: 2,
    date: "2024-09-02",
    type: "credit",
    description: "ZELLE TRANSFER FROM LISA MORRIS",
    transac: "Transfer",
    amount: 850,
  },
  {
    id: 3,
    date: "2024-09-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 800,
  },
  {
    id: 4,
    date: "2024-10-01",
    type: "credit",
    description: "INTEREST PAYMENT CITIBANK N.A.",
    transac: "Deposit",
    amount: 120,
  },
  {
    id: 5,
    date: "2024-10-18",
    type: "debit",
    description: "ONLINE TRANSFER TO CHK ####9876",
    transac: "Transfer",
    amount: 200,
  },
  {
    id: 6,
    date: "2024-11-05",
    type: "credit",
    description: "REFUND CHECK DEP POS #1109",
    transac: "Deposit",
    amount: 920,
  },
  {
    id: 7,
    date: "2024-11-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 900,
  },
  {
    id: 8,
    date: "2024-11-29",
    type: "debit",
    description: "ONLINE TRANSFER TO CHK ####9876",
    transac: "Transfer",
    amount: 300,
  },
  {
    id: 9,
    date: "2024-12-03",
    type: "credit",
    description: "ZELLE TRANSFER FROM DAVID CLARK",
    transac: "Transfer",
    amount: 650,
  },
  {
    id: 10,
    date: "2024-12-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 850,
  },
  {
    id: 11,
    date: "2025-01-02",
    type: "credit",
    description: "INTEREST PAYMENT CITIBANK N.A.",
    transac: "Deposit",
    amount: 205,
  },
  {
    id: 12,
    date: "2025-01-10",
    type: "debit",
    description: "ATM WDWL 44 MAIN ST BROOKLYN NY",
    transac: "ATM",
    amount: 200,
  },
  {
    id: 13,
    date: "2025-01-20",
    type: "credit",
    description: "INSURANCE REIMBURSEMENT DEP",
    transac: "Deposit",
    amount: 800,
  },
  {
    id: 14,
    date: "2025-02-05",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 850,
  },
  {
    id: 15,
    date: "2025-02-12",
    type: "debit",
    description: "ONLINE TRANSFER TO CHK ####9876",
    transac: "Transfer",
    amount: 400,
  },
  {
    id: 16,
    date: "2025-02-27",
    type: "credit",
    description: "ZELLE TRANSFER FROM JAMES WRIGHT",
    transac: "Transfer",
    amount: 880,
  },
  {
    id: 17,
    date: "2025-03-02",
    type: "credit",
    description: "INTEREST PAYMENT CITIBANK N.A.",
    transac: "Deposit",
    amount: 676,
  },
  {
    id: 18,
    date: "2025-03-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 800,
  },
  {
    id: 19,
    date: "2025-03-22",
    type: "debit",
    description: "ONLINE TRANSFER TO CHK ####9876",
    transac: "Transfer",
    amount: 275,
  },
  {
    id: 20,
    date: "2025-04-08",
    type: "credit",
    description: "ZELLE TRANSFER FROM MARY JOHNSON",
    transac: "Transfer",
    amount: 920,
  },
  {
    id: 21,
    date: "2025-04-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 800,
  },
  {
    id: 22,
    date: "2025-05-02",
    type: "credit",
    description: "INTEREST PAYMENT CITIBANK N.A.",
    transac: "Deposit",
    amount: 198,
  },
  {
    id: 23,
    date: "2025-05-06",
    type: "debit",
    description: "ONLINE TRANSFER TO CHK ####9876",
    transac: "Transfer",
    amount: 320,
  },
  {
    id: 24,
    date: "2025-05-20",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 450,
  },
  {
    id: 25,
    date: "2025-06-01",
    type: "credit",
    description: "ZELLE TRANSFER FROM KEVIN SMITH",
    transac: "Transfer",
    amount: 400,
  },
  {
    id: 26,
    date: "2025-06-12",
    type: "debit",
    description: "ATM WDWL 81 BROADWAY NEW YORK NY",
    transac: "ATM",
    amount: 250,
  },
  {
    id: 27,
    date: "2025-06-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 500,
  },
  {
    id: 28,
    date: "2025-07-01",
    type: "credit",
    description: "INTEREST PAYMENT CITIBANK N.A.",
    transac: "Deposit",
    amount: 19,
  },
  {
    id: 29,
    date: "2025-07-07",
    type: "credit",
    description: "ZELLE TRANSFER FROM ANTHONY WILSON",
    transac: "Transfer",
    amount: 460,
  },
  {
    id: 30,
    date: "2025-07-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 500,
  },
  {
    id: 31,
    date: "2025-08-05",
    type: "credit",
    description: "ZELLE TRANSFER FROM JASON MILLER",
    transac: "Transfer",
    amount: 390,
  },
  {
    id: 32,
    date: "2025-08-15",
    type: "credit",
    description: "CITIBANK AUTO SAVE TRANSFER",
    transac: "Deposit",
    amount: 550,
  },
  {
    id: 33,
    date: "2025-08-18",
    type: "debit",
    description: "ONLINE TRANSFER TO CHK ####9876",
    transac: "Transfer",
    amount: 300,
  },
  {
    id: 34,
    date: "2025-08-25",
    type: "credit",
    description: "INTEREST PAYMENT CITIBANK N.A.",
    transac: "Deposit",
    amount: 20,
  },
  {
    id: 35,
    date: "2025-08-28",
    type: "credit",
    description: "ZELLE TRANSFER FROM KAREN WHITE",
    transac: "Transfer",
    amount: 500,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
  // { id: 4, label: "Previous Years", value: "730" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
