// the transactionHistory
// export const transactions = [
//   {
//     id: 1,
//     date: "2024-05-20",
//     type: "debit",
//     description: "Payment to Credit Card - Citi",
//     transac: "Transfer",
//     amount: 11916,
//   },
//   {
//     id: 2,
//     date: "2024-05-31",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 58969,
//   },
//   {
//     id: 3,
//     date: "2024-06-08",
//     type: "debit",
//     description: "ATM Withdrawal - Los Angeles",
//     transac: "Debit Card",
//     amount: 6729,
//   },
//   {
//     id: 4,
//     date: "2024-06-14",
//     type: "credit",
//     description: "Returned Transaction Refund",
//     transac: "Transfer",
//     amount: 74465,
//   },
//   {
//     id: 5,
//     date: "2024-06-23",
//     type: "credit",
//     description: "Returned Transaction Refund",
//     transac: "Deposit",
//     amount: 55903,
//   },
//   {
//     id: 6,
//     date: "2024-06-28",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Transfer",
//     amount: 43843,
//   },
//   {
//     id: 7,
//     date: "2024-07-07",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Wire",
//     amount: 30506,
//   },
//   {
//     id: 8,
//     date: "2024-07-18",
//     type: "credit",
//     description: "Tax Refund - IRS",
//     transac: "Wire",
//     amount: 54917,
//   },
//   {
//     id: 9,
//     date: "2024-07-26",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Deposit",
//     amount: 73781,
//   },
//   {
//     id: 10,
//     date: "2024-08-06",
//     type: "debit",
//     description: "Health Insurance Premium",
//     transac: "Check",
//     amount: 4386,
//   },
//   {
//     id: 11,
//     date: "2024-08-18",
//     type: "debit",
//     description: "Coffee Shop - Starbucks",
//     transac: "Debit Card",
//     amount: 13258,
//   },
//   {
//     id: 12,
//     date: "2024-08-29",
//     type: "debit",
//     description: "Gas Station - Chevron",
//     transac: "Check",
//     amount: 16686,
//   },
//   {
//     id: 13,
//     date: "2024-09-09",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Wire",
//     amount: 51284,
//   },
//   {
//     id: 14,
//     date: "2024-09-21",
//     type: "debit",
//     description: "Monthly Rent Payment",
//     transac: "Debit Card",
//     amount: 14857,
//   },
//   {
//     id: 15,
//     date: "2024-09-27",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Wire",
//     amount: 68592,
//   },
//   {
//     id: 16,
//     date: "2024-10-03",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Deposit",
//     amount: 50334,
//   },
//   {
//     id: 17,
//     date: "2024-10-13",
//     type: "debit",
//     description: "Restaurant - Chipotle",
//     transac: "Transfer",
//     amount: 5502,
//   },
//   {
//     id: 18,
//     date: "2024-10-19",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Transfer",
//     amount: 42707,
//   },
//   {
//     id: 19,
//     date: "2024-10-26",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Deposit",
//     amount: 39597,
//   },
//   {
//     id: 20,
//     date: "2024-11-02",
//     type: "debit",
//     description: "Grocery Store - Trader Joe's",
//     transac: "Transfer",
//     amount: 5469,
//   },
//   {
//     id: 21,
//     date: "2024-11-14",
//     type: "credit",
//     description: "Returned Transaction Refund",
//     transac: "Transfer",
//     amount: 66944,
//   },
//   {
//     id: 22,
//     date: "2024-11-24",
//     type: "debit",
//     description: "Grocery Store - Trader Joe's",
//     transac: "Debit Card",
//     amount: 13359,
//   },
//   {
//     id: 23,
//     date: "2024-11-30",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Transfer",
//     amount: 71378,
//   },
//   {
//     id: 24,
//     date: "2024-12-05",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Transfer",
//     amount: 34862,
//   },
//   {
//     id: 25,
//     date: "2024-12-17",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Deposit",
//     amount: 54165,
//   },
//   {
//     id: 26,
//     date: "2024-12-23",
//     type: "debit",
//     description: "Health Insurance Premium",
//     transac: "Debit Card",
//     amount: 19615,
//   },
//   {
//     id: 27,
//     date: "2024-12-28",
//     type: "credit",
//     description: "Freelance Payment - CAD Design",
//     transac: "Transfer",
//     amount: 67464,
//   },
//   {
//     id: 28,
//     date: "2025-01-09",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Deposit",
//     amount: 34054,
//   },
//   {
//     id: 29,
//     date: "2025-01-19",
//     type: "debit",
//     description: "Restaurant - Chipotle",
//     transac: "Transfer",
//     amount: 5763,
//   },
//   {
//     id: 30,
//     date: "2025-01-26",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 76374,
//   },
//   {
//     id: 31,
//     date: "2025-02-02",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 48539,
//   },
//   {
//     id: 32,
//     date: "2025-02-12",
//     type: "debit",
//     description: "ATM Withdrawal - Los Angeles",
//     transac: "Check",
//     amount: 4715,
//   },
//   {
//     id: 33,
//     date: "2025-05-07",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 74458,
//   },
//   {
//     id: 34,
//     date: "2025-05-12",
//     type: "debit",
//     description: "Final Adjustment to Match Target Balance",
//     transac: "Transfer",
//     amount: 881,
//   },
// ];

// export const savingTransactions = [
//   {
//     id: 1,
//     date: "2024-05-27",
//     type: "debit",
//     description: "Payment to Credit Card - Citi",
//     transac: "Debit Card",
//     amount: 15496,
//   },
//   {
//     id: 2,
//     date: "2024-06-06",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Deposit",
//     amount: 76205,
//   },
//   {
//     id: 3,
//     date: "2024-06-13",
//     type: "credit",
//     description: "Direct Deposit: Engineering Salary",
//     transac: "Deposit",
//     amount: 50752,
//   },
//   {
//     id: 4,
//     date: "2024-06-21",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Deposit",
//     amount: 100136,
//   },
//   {
//     id: 5,
//     date: "2024-07-06",
//     type: "credit",
//     description: "Wire Transfer from Client - Project Alpha",
//     transac: "Wire",
//     amount: 97192,
//   },
//   {
//     id: 6,
//     date: "2024-07-14",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 81091,
//   },
//   {
//     id: 7,
//     date: "2024-07-26",
//     type: "debit",
//     description: "Utility Bill - Gas",
//     transac: "Check",
//     amount: 19785,
//   },
//   {
//     id: 8,
//     date: "2024-08-06",
//     type: "credit",
//     description: "Freelance Payment - CAD Design",
//     transac: "Transfer",
//     amount: 118833,
//   },
//   {
//     id: 9,
//     date: "2024-08-21",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Deposit",
//     amount: 103692,
//   },
//   {
//     id: 10,
//     date: "2024-09-03",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Transfer",
//     amount: 77550,
//   },
//   {
//     id: 11,
//     date: "2024-09-17",
//     type: "credit",
//     description: "Interest Earned on Savings Account",
//     transac: "Wire",
//     amount: 107420,
//   },
//   {
//     id: 12,
//     date: "2024-10-01",
//     type: "debit",
//     description: "Online Purchase - Amazon",
//     transac: "Transfer",
//     amount: 11665,
//   },
//   {
//     id: 13,
//     date: "2024-10-11",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Transfer",
//     amount: 115594,
//   },
//   {
//     id: 14,
//     date: "2024-10-22",
//     type: "debit",
//     description: "Online Purchase - Amazon",
//     transac: "Transfer",
//     amount: 15780,
//   },
//   {
//     id: 15,
//     date: "2024-11-03",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Deposit",
//     amount: 97263,
//   },
//   {
//     id: 16,
//     date: "2024-11-11",
//     type: "credit",
//     description: "Tax Refund - IRS",
//     transac: "Transfer",
//     amount: 77922,
//   },
//   {
//     id: 17,
//     date: "2024-11-23",
//     type: "credit",
//     description: "Direct Deposit: Engineering Salary",
//     transac: "Transfer",
//     amount: 80040,
//   },
//   {
//     id: 18,
//     date: "2024-12-03",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Wire",
//     amount: 56597,
//   },
//   {
//     id: 19,
//     date: "2024-12-11",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 81632,
//   },
//   {
//     id: 20,
//     date: "2024-12-26",
//     type: "credit",
//     description: "Wire Transfer from Client - Project Alpha",
//     transac: "Transfer",
//     amount: 64083,
//   },
//   {
//     id: 21,
//     date: "2025-01-10",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Wire",
//     amount: 53493,
//   },
//   {
//     id: 22,
//     date: "2025-01-21",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Wire",
//     amount: 60396,
//   },
//   {
//     id: 23,
//     date: "2025-01-29",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 119603,
//   },
//   {
//     id: 24,
//     date: "2025-02-07",
//     type: "debit",
//     description: "Coffee Shop - Starbucks",
//     transac: "Transfer",
//     amount: 7344,
//   },
//   {
//     id: 25,
//     date: "2025-02-21",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Deposit",
//     amount: 113066,
//   },
//   {
//     id: 26,
//     date: "2025-03-03",
//     type: "credit",
//     description: "Wire Transfer from Client - Project Alpha",
//     transac: "Deposit",
//     amount: 93890,
//   },
//   {
//     id: 27,
//     date: "2025-03-11",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 112155,
//   },
//   {
//     id: 28,
//     date: "2025-05-12",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Wire",
//     amount: 101428,
//   },
//   {
//     id: 29,
//     date: "2025-05-17",
//     type: "debit",
//     description: "Final Adjustment to Match Target Balance",
//     transac: "Transfer",
//     amount: 69963,
//   },
// ];

export const transactions = [
  {
    id: 1,
    date: "2024-07-01",
    type: "debit",
    description: "Uber - Official Transportation",
    transac: "Card",
    amount: 42,
  },
  {
    id: 2,
    date: "2024-07-19",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 15212,
  },
  {
    id: 3,
    date: "2024-07-20",
    type: "debit",
    description: "Payment to Blue Cross Blue Shield - Health Insurance",
    transac: "Transfer",
    amount: 742,
  },
  {
    id: 4,
    date: "2024-08-03",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 10774,
  },
  {
    id: 5,
    date: "2024-08-18",
    type: "credit",
    description: "Salary Deposit",
    transac: "Deposit",
    amount: 13036,
  },
  {
    id: 6,
    date: "2024-09-04",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 21967,
  },
  {
    id: 7,
    date: "2024-09-20",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 14332,
  },
  {
    id: 8,
    date: "2024-10-04",
    type: "credit",
    description: "Wire Transfer Received - Classified Project",
    transac: "Wire",
    amount: 18758,
  },
  {
    id: 9,
    date: "2024-10-18",
    type: "debit",
    description: "Amazon Purchase - Office Supplies",
    transac: "Card",
    amount: 172,
  },
  {
    id: 10,
    date: "2024-11-03",
    type: "credit",
    description: "Direct Deposit - US Department of Homeland Security Payroll",
    transac: "Deposit",
    amount: 14804,
  },
  {
    id: 11,
    date: "2024-11-20",
    type: "credit",
    description: "Paycheck Bonus - Intelligence Incentive",
    transac: "Deposit",
    amount: 3564,
  },
  {
    id: 12,
    date: "2024-12-01",
    type: "debit",
    description: "Dining - Mission BBQ",
    transac: "Card",
    amount: 96,
  },
  {
    id: 13,
    date: "2024-12-17",
    type: "debit",
    description: "Uber - Official Transportation",
    transac: "Card",
    amount: 53,
  },
  {
    id: 14,
    date: "2025-01-04",
    type: "credit",
    description: "Reimbursement - Travel Expense",
    transac: "Deposit",
    amount: 814,
  },
  {
    id: 15,
    date: "2025-01-19",
    type: "credit",
    description: "Salary Deposit",
    transac: "Deposit",
    amount: 14159,
  },
  {
    id: 16,
    date: "2025-02-03",
    type: "debit",
    description: "Amazon Purchase - Office Supplies",
    transac: "Card",
    amount: 98,
  },
  {
    id: 17,
    date: "2025-02-17",
    type: "credit",
    description: "Check Deposit - Refund from Supplier",
    transac: "Check",
    amount: 876,
  },
  {
    id: 18,
    date: "2025-03-01",
    type: "credit",
    description: "Paycheck Bonus - Intelligence Incentive",
    transac: "Deposit",
    amount: 4015,
  },
  {
    id: 19,
    date: "2025-03-18",
    type: "debit",
    description: "Dining - Mission BBQ",
    transac: "Card",
    amount: 43,
  },
  {
    id: 20,
    date: "2025-04-04",
    type: "credit",
    description: "Direct Deposit - US Department of Homeland Security Payroll",
    transac: "Deposit",
    amount: 14768,
  },
  {
    id: 21,
    date: "2025-04-20",
    type: "credit",
    description: "Reimbursement - Travel Expense",
    transac: "Deposit",
    amount: 912,
  },
  {
    id: 22,
    date: "2025-05-05",
    type: "credit",
    description: "Wire Transfer Received - Classified Project",
    transac: "Wire",
    amount: 14233,
  },
  {
    id: 23,
    date: "2025-05-21",
    type: "debit",
    description: "Payment to Blue Cross Blue Shield - Health Insurance",
    transac: "Transfer",
    amount: 726,
  },
  {
    id: 24,
    date: "2025-06-06",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 18604,
  },
  {
    id: 25,
    date: "2025-06-15",
    type: "debit",
    description: "Uber - Official Transportation",
    transac: "Card",
    amount: 33,
  },
  {
    id: 26,
    date: "2024-06-11",
    type: "credit",
    description: "Direct Deposit - US Department of Homeland Security Payroll",
    transac: "Deposit",
    amount: 12473,
  },
  {
    id: 27,
    date: "2024-07-03",
    type: "debit",
    description: "Dining - Mission BBQ",
    transac: "Card",
    amount: 69,
  },
  {
    id: 28,
    date: "2024-08-02",
    type: "credit",
    description: "Paycheck Bonus - Intelligence Incentive",
    transac: "Deposit",
    amount: 4532,
  },
  {
    id: 29,
    date: "2024-09-06",
    type: "debit",
    description: "Dining - Mission BBQ",
    transac: "Card",
    amount: 71,
  },
  {
    id: 30,
    date: "2024-10-01",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 29703,
  },
  {
    id: 31,
    date: "2024-11-02",
    type: "debit",
    description: "Uber - Official Transportation",
    transac: "Card",
    amount: 47,
  },
  {
    id: 32,
    date: "2024-12-04",
    type: "credit",
    description: "Reimbursement - Travel Expense",
    transac: "Deposit",
    amount: 613,
  },
  {
    id: 33,
    date: "2025-01-03",
    type: "credit",
    description: "Direct Deposit - US Department of Homeland Security Payroll",
    transac: "Deposit",
    amount: 13746,
  },
  {
    id: 34,
    date: "2025-02-05",
    type: "credit",
    description: "Salary Deposit",
    transac: "Deposit",
    amount: 14482,
  },
  {
    id: 35,
    date: "2025-03-07",
    type: "debit",
    description: "Amazon Purchase - Office Supplies",
    transac: "Card",
    amount: 183,
  },
  {
    id: 36,
    date: "2025-04-06",
    type: "debit",
    description: "Payment to Blue Cross Blue Shield - Health Insurance",
    transac: "Transfer",
    amount: 588,
  },
  {
    id: 37,
    date: "2025-05-04",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 17996,
  },
  {
    id: 38,
    date: "2025-06-03",
    type: "credit",
    description: "Check Deposit - Refund from Supplier",
    transac: "Check",
    amount: 933,
  },
  {
    id: 39,
    date: "2024-06-18",
    type: "debit",
    description: "Amazon Purchase - Office Supplies",
    transac: "Card",
    amount: 66,
  },
  {
    id: 40,
    date: "2024-07-06",
    type: "debit",
    description: "Dining - Mission BBQ",
    transac: "Card",
    amount: 88,
  },
  {
    id: 41,
    date: "2024-08-05",
    type: "credit",
    description: "Salary Deposit",
    transac: "Deposit",
    amount: 13943,
  },
  {
    id: 42,
    date: "2024-09-07",
    type: "credit",
    description: "Wire Transfer Received - Classified Project",
    transac: "Wire",
    amount: 15538,
  },
  {
    id: 43,
    date: "2024-10-05",
    type: "credit",
    description: "Reimbursement - Travel Expense",
    transac: "Deposit",
    amount: 724,
  },
  {
    id: 44,
    date: "2024-11-06",
    type: "credit",
    description: "Salary Deposit",
    transac: "Deposit",
    amount: 13321,
  },
  {
    id: 45,
    date: "2024-12-06",
    type: "debit",
    description: "Dining - Mission BBQ",
    transac: "Card",
    amount: 91,
  },
  {
    id: 46,
    date: "2025-01-06",
    type: "debit",
    description: "Transfer to Savings Account",
    transac: "Transfer",
    amount: 16204,
  },
  {
    id: 47,
    date: "2025-02-06",
    type: "debit",
    description: "Uber - Official Transportation",
    transac: "Card",
    amount: 36,
  },
  {
    id: 48,
    date: "2025-03-06",
    type: "debit",
    description: "Payment to Blue Cross Blue Shield - Health Insurance",
    transac: "Transfer",
    amount: 693,
  },
  {
    id: 49,
    date: "2025-04-07",
    type: "credit",
    description: "Check Deposit - Refund from Supplier",
    transac: "Check",
    amount: 1092,
  },
  {
    id: 50,
    date: "2025-05-07",
    type: "credit",
    description: "Direct Deposit - US Department of Homeland Security Payroll",
    transac: "Deposit",
    amount: 15003,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2024-07-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 150212,
  },
  {
    id: 2,
    date: "2024-08-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 300774,
  },
  {
    id: 3,
    date: "2024-08-09",
    type: "credit",
    description: "Wire Transfer from Federal Contract",
    transac: "Wire",
    amount: 990857,
  },
  {
    id: 4,
    date: "2024-09-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 370158,
  },
  {
    id: 5,
    date: "2024-09-30",
    type: "debit",
    description: "Deposit from Classified Intel Bonus",
    transac: "Deposit",
    amount: 489000,
  },
  {
    id: 6,
    date: "2024-10-01",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 297903,
  },
  {
    id: 7,
    date: "2024-10-15",
    type: "debit",
    description: "High Interest Savings Yield",
    transac: "Deposit",
    amount: 17989,
  },
  {
    id: 8,
    date: "2024-11-01",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 307614,
  },
  {
    id: 9,
    date: "2024-11-29",
    type: "credit",
    description: "Wire Transfer from Federal Assignment",
    transac: "Wire",
    amount: 123964,
  },
  {
    id: 10,
    date: "2024-12-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 188765,
  },
  {
    id: 11,
    date: "2024-12-28",
    type: "credit",
    description: "End of Year Clearance Fund",
    transac: "Deposit",
    amount: 2728970,
  },
  {
    id: 12,
    date: "2025-01-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 314722,
  },
  {
    id: 13,
    date: "2025-01-17",
    type: "credit",
    description: "Bonus Deposit - Cyber Intelligence Division",
    transac: "Deposit",
    amount: 459970,
  },
  {
    id: 14,
    date: "2025-01-27",
    type: "debit",
    description: "Interest Yield",
    transac: "Deposit",
    amount: 19880,
  },
  {
    id: 15,
    date: "2025-02-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 28930,
  },
  {
    id: 16,
    date: "2025-02-25",
    type: "credit",
    description: "Classified Foreign Intelligence Reward",
    transac: "Deposit",
    amount: 85000,
  },
  {
    id: 17,
    date: "2025-03-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 33602,
  },
  {
    id: 18,
    date: "2025-03-15",
    type: "credit",
    description: "Check Deposit from Secure Source",
    transac: "Check",
    amount: 43000,
  },
  {
    id: 19,
    date: "2025-03-30",
    type: "credit",
    description: "Federal Security Allowance",
    transac: "Wire",
    amount: 110000,
  },
  {
    id: 20,
    date: "2025-04-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 36989,
  },
  {
    id: 21,
    date: "2025-04-20",
    type: "debit",
    description: "Reimbursement for Covert Operations",
    transac: "Deposit",
    amount: 624258,
  },
  {
    id: 22,
    date: "2025-04-30",
    type: "credit",
    description: "Savings Interest",
    transac: "Deposit",
    amount: 2115,
  },
  {
    id: 23,
    date: "2025-05-03",
    type: "credit",
    description: "Monthly Transfer from Checking",
    transac: "Transfer",
    amount: 307996,
  },
  {
    id: 24,
    date: "2025-05-19",
    type: "debit",
    description: "Check Deposit - Equipment Liquidation",
    transac: "Check",
    amount: 382811,
  },
  {
    id: 25,
    date: "2025-05-31",
    type: "debit",
    description: "Annual Fund Incentive",
    transac: "Wire",
    amount: 95000,
  },
  {
    id: 26,
    date: "2024-07-11",
    type: "credit",
    description: "Direct Deposit - Covert Bonus",
    transac: "Deposit",
    amount: 78521,
  },
  {
    id: 27,
    date: "2024-08-22",
    type: "debit",
    description: "Savings Deposit - Project Fund Holdover",
    transac: "Deposit",
    amount: 66034,
  },
  {
    id: 28,
    date: "2024-09-11",
    type: "debit",
    description: "Reimbursement - Risk Operation",
    transac: "Deposit",
    amount: 58021,
  },
  {
    id: 29,
    date: "2024-10-12",
    type: "credit",
    description: "Check Deposit - Surveillance Payout",
    transac: "Check",
    amount: 447900,
  },
  {
    id: 30,
    date: "2024-11-10",
    type: "debit",
    description: "Deposit - Strategic Contingency Payout",
    transac: "Deposit",
    amount: 74000,
  },
  {
    id: 31,
    date: "2024-12-12",
    type: "credit",
    description: "Savings Deposit - Year End Review",
    transac: "Deposit",
    amount: 68021,
  },
  {
    id: 32,
    date: "2025-01-12",
    type: "debit",
    description: "Bonus - Tech Counterintelligence",
    transac: "Deposit",
    amount: 52480,
  },
  {
    id: 33,
    date: "2025-02-11",
    type: "credit",
    description: "Check - Clearance Rebate",
    transac: "Check",
    amount: 280810,
  },
  {
    id: 34,
    date: "2025-03-12",
    type: "debit",
    description: "Wire - High Risk Reward",
    transac: "Wire",
    amount: 115000,
  },
  {
    id: 35,
    date: "2025-04-12",
    type: "debit",
    description: "Transfer from Investment Payout",
    transac: "Transfer",
    amount: 97400,
  },
  {
    id: 36,
    date: "2025-05-12",
    type: "debit",
    description: "Special Deposit - Joint Agency Project",
    transac: "Deposit",
    amount: 68700,
  },
  {
    id: 37,
    date: "2025-06-02",
    type: "credit",
    description: "Deposit - Covert Operation Allowance",
    transac: "Deposit",
    amount: 452814,
  },
  {
    id: 38,
    date: "2024-06-01",
    type: "debit",
    description: "Deposit - Operation Logistics Rollover",
    transac: "Deposit",
    amount: 65420,
  },
  {
    id: 39,
    date: "2024-06-20",
    type: "credit",
    description: "Wire Transfer - Joint Taskforce Credit",
    transac: "Wire",
    amount: 78090,
  },
  {
    id: 40,
    date: "2024-07-25",
    type: "credit",
    description: "Transfer from Checking Account",
    transac: "Transfer",
    amount: 33000,
  },
  {
    id: 41,
    date: "2024-08-12",
    type: "credit",
    description: "Check - Clearance Travel Refund",
    transac: "Check",
    amount: 29400,
  },
  {
    id: 42,
    date: "2024-09-25",
    type: "credit",
    description: "Deposit - Taskforce Safety Bonus",
    transac: "Deposit",
    amount: 34700,
  },
  {
    id: 43,
    date: "2024-10-28",
    type: "credit",
    description: "Interest Credit",
    transac: "Deposit",
    amount: 1289,
  },
  {
    id: 44,
    date: "2024-11-27",
    type: "credit",
    description: "Direct Deposit - Holiday Adjustment",
    transac: "Deposit",
    amount: 145000,
  },
  {
    id: 45,
    date: "2024-12-25",
    type: "credit",
    description: "Wire Transfer - Secure Contingency Fund",
    transac: "Wire",
    amount: 60000,
  },
  {
    id: 46,
    date: "2025-01-27",
    type: "credit",
    description: "Savings Interest",
    transac: "Deposit",
    amount: 1991,
  },
  {
    id: 47,
    date: "2025-02-28",
    type: "debit",
    description: "Classified Intel Project Funding",
    transac: "Deposit",
    amount: 98400,
  },
  {
    id: 48,
    date: "2025-03-27",
    type: "debit",
    description: "Deposit - Federal Reserve Adjustment",
    transac: "Deposit",
    amount: 33350,
  },
  {
    id: 49,
    date: "2025-04-25",
    type: "credit",
    description: "Check - Secure Logistics Claim",
    transac: "Check",
    amount: 439200,
  },
  {
    id: 50,
    date: "2025-05-30",
    type: "debit",
    description: "Wire Transfer - Intel Taskforce Fund",
    transac: "Wire",
    amount: 75500,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
