// the transactionHistory
// export const transactions = [
//   {
//     id: 1,
//     date: "2024-05-20",
//     type: "debit",
//     description: "Payment to Credit Card - Citi",
//     transac: "Transfer",
//     amount: 11916,
//   },
//   {
//     id: 2,
//     date: "2024-05-31",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 58969,
//   },
//   {
//     id: 3,
//     date: "2024-06-08",
//     type: "debit",
//     description: "ATM Withdrawal - Los Angeles",
//     transac: "Debit Card",
//     amount: 6729,
//   },
//   {
//     id: 4,
//     date: "2024-06-14",
//     type: "credit",
//     description: "Returned Transaction Refund",
//     transac: "Transfer",
//     amount: 74465,
//   },
//   {
//     id: 5,
//     date: "2024-06-23",
//     type: "credit",
//     description: "Returned Transaction Refund",
//     transac: "Deposit",
//     amount: 55903,
//   },
//   {
//     id: 6,
//     date: "2024-06-28",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Transfer",
//     amount: 43843,
//   },
//   {
//     id: 7,
//     date: "2024-07-07",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Wire",
//     amount: 30506,
//   },
//   {
//     id: 8,
//     date: "2024-07-18",
//     type: "credit",
//     description: "Tax Refund - IRS",
//     transac: "Wire",
//     amount: 54917,
//   },
//   {
//     id: 9,
//     date: "2024-07-26",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Deposit",
//     amount: 73781,
//   },
//   {
//     id: 10,
//     date: "2024-08-06",
//     type: "debit",
//     description: "Health Insurance Premium",
//     transac: "Check",
//     amount: 4386,
//   },
//   {
//     id: 11,
//     date: "2024-08-18",
//     type: "debit",
//     description: "Coffee Shop - Starbucks",
//     transac: "Debit Card",
//     amount: 13258,
//   },
//   {
//     id: 12,
//     date: "2024-08-29",
//     type: "debit",
//     description: "Gas Station - Chevron",
//     transac: "Check",
//     amount: 16686,
//   },
//   {
//     id: 13,
//     date: "2024-09-09",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Wire",
//     amount: 51284,
//   },
//   {
//     id: 14,
//     date: "2024-09-21",
//     type: "debit",
//     description: "Monthly Rent Payment",
//     transac: "Debit Card",
//     amount: 14857,
//   },
//   {
//     id: 15,
//     date: "2024-09-27",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Wire",
//     amount: 68592,
//   },
//   {
//     id: 16,
//     date: "2024-10-03",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Deposit",
//     amount: 50334,
//   },
//   {
//     id: 17,
//     date: "2024-10-13",
//     type: "debit",
//     description: "Restaurant - Chipotle",
//     transac: "Transfer",
//     amount: 5502,
//   },
//   {
//     id: 18,
//     date: "2024-10-19",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Transfer",
//     amount: 42707,
//   },
//   {
//     id: 19,
//     date: "2024-10-26",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Deposit",
//     amount: 39597,
//   },
//   {
//     id: 20,
//     date: "2024-11-02",
//     type: "debit",
//     description: "Grocery Store - Trader Joe's",
//     transac: "Transfer",
//     amount: 5469,
//   },
//   {
//     id: 21,
//     date: "2024-11-14",
//     type: "credit",
//     description: "Returned Transaction Refund",
//     transac: "Transfer",
//     amount: 66944,
//   },
//   {
//     id: 22,
//     date: "2024-11-24",
//     type: "debit",
//     description: "Grocery Store - Trader Joe's",
//     transac: "Debit Card",
//     amount: 13359,
//   },
//   {
//     id: 23,
//     date: "2024-11-30",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Transfer",
//     amount: 71378,
//   },
//   {
//     id: 24,
//     date: "2024-12-05",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Transfer",
//     amount: 34862,
//   },
//   {
//     id: 25,
//     date: "2024-12-17",
//     type: "credit",
//     description: "Interest Earned on Checking Account",
//     transac: "Deposit",
//     amount: 54165,
//   },
//   {
//     id: 26,
//     date: "2024-12-23",
//     type: "debit",
//     description: "Health Insurance Premium",
//     transac: "Debit Card",
//     amount: 19615,
//   },
//   {
//     id: 27,
//     date: "2024-12-28",
//     type: "credit",
//     description: "Freelance Payment - CAD Design",
//     transac: "Transfer",
//     amount: 67464,
//   },
//   {
//     id: 28,
//     date: "2025-01-09",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Deposit",
//     amount: 34054,
//   },
//   {
//     id: 29,
//     date: "2025-01-19",
//     type: "debit",
//     description: "Restaurant - Chipotle",
//     transac: "Transfer",
//     amount: 5763,
//   },
//   {
//     id: 30,
//     date: "2025-01-26",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 76374,
//   },
//   {
//     id: 31,
//     date: "2025-02-02",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 48539,
//   },
//   {
//     id: 32,
//     date: "2025-02-12",
//     type: "debit",
//     description: "ATM Withdrawal - Los Angeles",
//     transac: "Check",
//     amount: 4715,
//   },
//   {
//     id: 33,
//     date: "2025-05-07",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 74458,
//   },
//   {
//     id: 34,
//     date: "2025-05-12",
//     type: "debit",
//     description: "Final Adjustment to Match Target Balance",
//     transac: "Transfer",
//     amount: 881,
//   },
// ];

// export const savingTransactions = [
//   {
//     id: 1,
//     date: "2024-05-27",
//     type: "debit",
//     description: "Payment to Credit Card - Citi",
//     transac: "Debit Card",
//     amount: 15496,
//   },
//   {
//     id: 2,
//     date: "2024-06-06",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Deposit",
//     amount: 76205,
//   },
//   {
//     id: 3,
//     date: "2024-06-13",
//     type: "credit",
//     description: "Direct Deposit: Engineering Salary",
//     transac: "Deposit",
//     amount: 50752,
//   },
//   {
//     id: 4,
//     date: "2024-06-21",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Deposit",
//     amount: 100136,
//   },
//   {
//     id: 5,
//     date: "2024-07-06",
//     type: "credit",
//     description: "Wire Transfer from Client - Project Alpha",
//     transac: "Wire",
//     amount: 97192,
//   },
//   {
//     id: 6,
//     date: "2024-07-14",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 81091,
//   },
//   {
//     id: 7,
//     date: "2024-07-26",
//     type: "debit",
//     description: "Utility Bill - Gas",
//     transac: "Check",
//     amount: 19785,
//   },
//   {
//     id: 8,
//     date: "2024-08-06",
//     type: "credit",
//     description: "Freelance Payment - CAD Design",
//     transac: "Transfer",
//     amount: 118833,
//   },
//   {
//     id: 9,
//     date: "2024-08-21",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Deposit",
//     amount: 103692,
//   },
//   {
//     id: 10,
//     date: "2024-09-03",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Transfer",
//     amount: 77550,
//   },
//   {
//     id: 11,
//     date: "2024-09-17",
//     type: "credit",
//     description: "Interest Earned on Savings Account",
//     transac: "Wire",
//     amount: 107420,
//   },
//   {
//     id: 12,
//     date: "2024-10-01",
//     type: "debit",
//     description: "Online Purchase - Amazon",
//     transac: "Transfer",
//     amount: 11665,
//   },
//   {
//     id: 13,
//     date: "2024-10-11",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Transfer",
//     amount: 115594,
//   },
//   {
//     id: 14,
//     date: "2024-10-22",
//     type: "debit",
//     description: "Online Purchase - Amazon",
//     transac: "Transfer",
//     amount: 15780,
//   },
//   {
//     id: 15,
//     date: "2024-11-03",
//     type: "credit",
//     description: "Deposit from Friend",
//     transac: "Deposit",
//     amount: 97263,
//   },
//   {
//     id: 16,
//     date: "2024-11-11",
//     type: "credit",
//     description: "Tax Refund - IRS",
//     transac: "Transfer",
//     amount: 77922,
//   },
//   {
//     id: 17,
//     date: "2024-11-23",
//     type: "credit",
//     description: "Direct Deposit: Engineering Salary",
//     transac: "Transfer",
//     amount: 80040,
//   },
//   {
//     id: 18,
//     date: "2024-12-03",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Wire",
//     amount: 56597,
//   },
//   {
//     id: 19,
//     date: "2024-12-11",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 81632,
//   },
//   {
//     id: 20,
//     date: "2024-12-26",
//     type: "credit",
//     description: "Wire Transfer from Client - Project Alpha",
//     transac: "Transfer",
//     amount: 64083,
//   },
//   {
//     id: 21,
//     date: "2025-01-10",
//     type: "credit",
//     description: "Refund from Apple Store",
//     transac: "Wire",
//     amount: 53493,
//   },
//   {
//     id: 22,
//     date: "2025-01-21",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Wire",
//     amount: 60396,
//   },
//   {
//     id: 23,
//     date: "2025-01-29",
//     type: "credit",
//     description: "Bonus: End-of-Year Payout",
//     transac: "Transfer",
//     amount: 119603,
//   },
//   {
//     id: 24,
//     date: "2025-02-07",
//     type: "debit",
//     description: "Coffee Shop - Starbucks",
//     transac: "Transfer",
//     amount: 7344,
//   },
//   {
//     id: 25,
//     date: "2025-02-21",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Deposit",
//     amount: 113066,
//   },
//   {
//     id: 26,
//     date: "2025-03-03",
//     type: "credit",
//     description: "Wire Transfer from Client - Project Alpha",
//     transac: "Deposit",
//     amount: 93890,
//   },
//   {
//     id: 27,
//     date: "2025-03-11",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Transfer",
//     amount: 112155,
//   },
//   {
//     id: 28,
//     date: "2025-05-12",
//     type: "credit",
//     description: "Dividend Payment - Index Fund",
//     transac: "Wire",
//     amount: 101428,
//   },
//   {
//     id: 29,
//     date: "2025-05-17",
//     type: "debit",
//     description: "Final Adjustment to Match Target Balance",
//     transac: "Transfer",
//     amount: 69963,
//   },
// ];

export const transactions = [
  {
    id: 1,
    date: "2024-07-18",
    type: "credit",
    description: "Property Rent Income - ACH Deposit",
    transac: "Deposit",
    amount: 42500,
  },
  {
    id: 2,
    date: "2024-07-25",
    type: "debit",
    description: "BTC Purchase - Coinbase",
    transac: "Transfer",
    amount: 9671,
  },
  {
    id: 3,
    date: "2024-08-03",
    type: "debit",
    description: "Zelle Transfer to Contractor",
    transac: "Transfer",
    amount: 8700,
  },
  {
    id: 4,
    date: "2024-08-12",
    type: "credit",
    description: "Airbnb Rent Payment - ACH",
    transac: "Deposit",
    amount: 9980,
  },
  {
    id: 5,
    date: "2024-08-16",
    type: "debit",
    description: "OpenSea NFT Purchase",
    transac: "Transfer",
    amount: 9798,
  },
  {
    id: 6,
    date: "2024-08-27",
    type: "debit",
    description: "Remodeling Supplies - Home Depot",
    transac: "Check",
    amount: 7909,
  },
  {
    id: 7,
    date: "2024-09-04",
    type: "credit",
    description: "USDT Sell Proceeds - Kraken",
    transac: "Deposit",
    amount: 80200,
  },
  {
    id: 8,
    date: "2024-09-16",
    type: "debit",
    description: "Crypto Mining Fee - Bitmain",
    transac: "Transfer",
    amount: 7398,
  },
  {
    id: 9,
    date: "2024-10-01",
    type: "credit",
    description: "Tenant Rent Payment - Wire",
    transac: "Deposit",
    amount: 94500,
  },
  {
    id: 10,
    date: "2024-10-08",
    type: "debit",
    description: "Landscaping Service - Zelle",
    transac: "Transfer",
    amount: 2200,
  },
  {
    id: 11,
    date: "2024-10-22",
    type: "debit",
    description: "Ethereum Staking Platform Fee",
    transac: "Transfer",
    amount: 2500,
  },
  {
    id: 12,
    date: "2024-11-05",
    type: "credit",
    description: "Crypto Token Sale - ACH Deposit",
    transac: "Deposit",
    amount: 9900,
  },
  {
    id: 13,
    date: "2024-11-19",
    type: "debit",
    description: "Home Insurance Payment",
    transac: "Check",
    amount: 1600,
  },
  {
    id: 14,
    date: "2024-12-04",
    type: "credit",
    description: "Real Estate Investment Payout",
    transac: "Deposit",
    amount: 71500,
  },
  {
    id: 15,
    date: "2024-12-21",
    type: "debit",
    description: "Christmas Bonus to Employees",
    transac: "Check",
    amount: 4800,
  },
  {
    id: 16,
    date: "2025-01-09",
    type: "credit",
    description: "NFT Sales Proceeds - ETH to USD",
    transac: "Deposit",
    amount: 8200,
  },
  {
    id: 17,
    date: "2025-01-22",
    type: "debit",
    description: "Gas Fee for Token Swap",
    transac: "Transfer",
    amount: 300,
  },
  {
    id: 18,
    date: "2025-02-11",
    type: "credit",
    description: "New Rental Lease Payment",
    transac: "Deposit",
    amount: 87800,
  },
  {
    id: 19,
    date: "2025-02-23",
    type: "debit",
    description: "Zelle to Property Agent",
    transac: "Transfer",
    amount: 5400,
  },
  {
    id: 20,
    date: "2025-03-05",
    type: "credit",
    description: "Solana Coin Sale - Robinhood",
    transac: "Deposit",
    amount: 9200,
  },
  {
    id: 21,
    date: "2025-03-18",
    type: "debit",
    description: "Crypto Tax Payment - IRS",
    transac: "Transfer",
    amount: 15800,
  },
  {
    id: 22,
    date: "2025-04-01",
    type: "credit",
    description: "Tenant Security Deposit Refund",
    transac: "Deposit",
    amount: 9812,
  },
  {
    id: 23,
    date: "2025-04-12",
    type: "debit",
    description: "Maintenance & Repairs",
    transac: "Check",
    amount: 6900,
  },
  {
    id: 24,
    date: "2025-05-06",
    type: "credit",
    description: "Ethereum Sale Payout - Kraken",
    transac: "Deposit",
    amount: 9882,
  },
  {
    id: 25,
    date: "2025-05-14",
    type: "debit",
    description: "Zelle to Developer (DApp)",
    transac: "Transfer",
    amount: 4200,
  },
  {
    id: 26,
    date: "2025-06-01",
    type: "credit",
    description: "New Tenant Lease Payment",
    transac: "Deposit",
    amount: 98700,
  },
  {
    id: 27,
    date: "2025-06-17",
    type: "debit",
    description: "Virtual Office Subscription",
    transac: "Transfer",
    amount: 900,
  },
  {
    id: 28,
    date: "2025-06-29",
    type: "debit",
    description: "BTC Buy - Binance",
    transac: "Transfer",
    amount: 9871,
  },
  {
    id: 29,
    date: "2025-07-03",
    type: "credit",
    description: "Real Estate Flipping Profit",
    transac: "Deposit",
    amount: 25200,
  },
  {
    id: 30,
    date: "2025-07-06",
    type: "debit",
    description: "Legal Fees - Property Contract",
    transac: "Check",
    amount: 9182,
  },
];

export const savingTransactions = [
  {
    id: 1,
    date: "2024-07-05",
    type: "credit",
    description: "Monthly Interest Credit",
    transac: "Deposit",
    amount: 7240,
  },
  {
    id: 2,
    date: "2024-07-15",
    type: "credit",
    description: "Transfer from Checking",
    transac: "Transfer",
    amount: 98871,
  },
  {
    id: 3,
    date: "2024-08-01",
    type: "credit",
    description: "Real Estate Closing Profit",
    transac: "Deposit",
    amount: 98981,
  },
  {
    id: 4,
    date: "2024-08-27",
    type: "debit",
    description: "Crypto Investment Withdrawal",
    transac: "Transfer",
    amount: 15000,
  },
  {
    id: 5,
    date: "2024-09-03",
    type: "credit",
    description: "Ethereum Mining Return",
    transac: "Deposit",
    amount: 69182,
  },
  {
    id: 6,
    date: "2024-09-24",
    type: "credit",
    description: "Crypto Airdrop Bonus",
    transac: "Deposit",
    amount: 7800,
  },
  {
    id: 7,
    date: "2024-10-07",
    type: "credit",
    description: "Rental Property ROI",
    transac: "Deposit",
    amount: 81290,
  },
  {
    id: 8,
    date: "2024-10-21",
    type: "debit",
    description: "USDT Transfer to Trading Wallet",
    transac: "Transfer",
    amount: 5000,
  },
  {
    id: 9,
    date: "2024-11-01",
    type: "credit",
    description: "BNB Staking Rewards",
    transac: "Deposit",
    amount: 8200,
  },
  {
    id: 10,
    date: "2024-11-16",
    type: "credit",
    description: "Property Sale Proceeds",
    transac: "Deposit",
    amount: 58500,
  },
  {
    id: 11,
    date: "2024-12-01",
    type: "credit",
    description: "Interest Credit",
    transac: "Deposit",
    amount: 310,
  },
  {
    id: 12,
    date: "2024-12-15",
    type: "debit",
    description: "Transfer to Checking",
    transac: "Transfer",
    amount: 20000,
  },
  {
    id: 13,
    date: "2025-01-03",
    type: "credit",
    description: "Crypto Fund Deposit",
    transac: "Deposit",
    amount: 91738,
  },
  {
    id: 14,
    date: "2025-01-20",
    type: "credit",
    description: "USDT Interest - Stable Fund",
    transac: "Deposit",
    amount: 7261,
  },
  {
    id: 15,
    date: "2025-02-05",
    type: "credit",
    description: "Crypto Profit Sharing",
    transac: "Deposit",
    amount: 71920,
  },
  {
    id: 16,
    date: "2025-02-28",
    type: "debit",
    description: "Crypto Investment Purchase",
    transac: "Transfer",
    amount: 10000,
  },
  {
    id: 17,
    date: "2025-03-12",
    type: "credit",
    description: "Property Appreciation Payout",
    transac: "Deposit",
    amount: 72891,
  },
  {
    id: 18,
    date: "2025-03-30",
    type: "credit",
    description: "Interest Credit",
    transac: "Deposit",
    amount: 400,
  },
  {
    id: 19,
    date: "2025-04-07",
    type: "debit",
    description: "Transfer to Checking",
    transac: "Transfer",
    amount: 5000,
  },
  {
    id: 20,
    date: "2025-04-22",
    type: "credit",
    description: "Crypto Fund Performance Bonus",
    transac: "Deposit",
    amount: 7900,
  },
  {
    id: 21,
    date: "2025-05-03",
    type: "credit",
    description: "BNB Farming Profit",
    transac: "Deposit",
    amount: 6728,
  },
  {
    id: 22,
    date: "2025-05-17",
    type: "debit",
    description: "Transfer to Exchange Wallet",
    transac: "Transfer",
    amount: 8000,
  },
  {
    id: 23,
    date: "2025-06-01",
    type: "credit",
    description: "Interest Credit",
    transac: "Deposit",
    amount: 260,
  },
  {
    id: 24,
    date: "2025-06-10",
    type: "credit",
    description: "REIT Dividend Payment",
    transac: "Deposit",
    amount: 9918,
  },
  {
    id: 25,
    date: "2025-06-21",
    type: "debit",
    description: "Transfer to Checking",
    transac: "Transfer",
    amount: 15000,
  },
  {
    id: 26,
    date: "2025-07-01",
    type: "credit",
    description: "Crypto Project Royalty",
    transac: "Deposit",
    amount: 81920,
  },
  {
    id: 27,
    date: "2025-07-02",
    type: "credit",
    description: "Interest Credit",
    transac: "Deposit",
    amount: 330,
  },
  {
    id: 28,
    date: "2025-07-05",
    type: "credit",
    description: "Monthly Deposit - Property Trust",
    transac: "Deposit",
    amount: 9102,
  },
  {
    id: 29,
    date: "2025-07-06",
    type: "credit",
    description: "Ethereum Yield Farming Return",
    transac: "Deposit",
    amount: 7600,
  },
  {
    id: 30,
    date: "2025-07-07",
    type: "credit",
    description: "Crypto Fund Final Quarterly Payout",
    transac: "Deposit",
    amount: 10900,
  },
];

// Selected Date
export const timeOptions = [
  { id: 5, label: "Last 7 Days", value: "7" },
  { id: 1, label: "Last 30 Days", value: "30" },
  { id: 2, label: "Last 3 Months", value: "90" },
  { id: 3, label: "Last 6 Months", value: "180" },
  { id: 4, label: "Last 12 Months", value: "365" },
];

// Selected By Debit Or Credit
export const typeOptions = [
  { id: 1, label: "Show All", value: "all" },
  { id: 2, label: "Debits", value: "debit" },
  { id: 3, label: "Credits", value: "credit" },
];

import { PiFileTextLight } from "react-icons/pi";
import { SlPrinter } from "react-icons/sl";

// Records of Statement
export const statement = [
  { id: 1, label: "View Last Statement", value: PiFileTextLight },
  { id: 2, label: "Print", value: SlPrinter },
];
